version: "3.8" # Compose file 버전

volumes:
  postgres_db: {}
  static_volume:

services: # 이 아래로 서비스들을 적는다
  django: # 서비스의 이름을 django로 지정
    container_name: django # 컨테이너 이름을 지정
    build: . # docker build를 실행할 경로
    restart: always
    command: gunicorn example.wsgi --bind 0.0.0.0:8000
    expose:
      - "8000"
    volumes: # docker의 -volume 과 같은 부분
      - ./static:./staticfiles
    depends_on: # 서비스간의 종속성 순서대로 서비스를 시작한다. eg)db 실행 이후 django가 실행됨
      - db
    environment: # docker의 -e 와 같은 부분
      - DJANGO_DEBUG=False
      - DJANGO_SECRET_KEY=
      - DJANGO_ALLOWED_HOST=localhost
      - SQL_DATABASE=pgdb
      - SQL_USER=pguser
      - SQL_PASSWORD=pgpass
      - SQL_HOST=db
      - SQL_PORT=5432
  db:
    container_name: db
    image: postgres
    environment: 
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgres/data
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/staticfiles
    depends_on:
      - django