version: "3.8" # Compose file 버전

volumes:
  postgres_db: {}

services:
  django:
    container_name: django
    build: . 
    restart: always
    command: gunicorn dcmStatus.wsgi --bind 0.0.0.0:8000
    ports:
      - 80:8000
    volumes:
      - .:/web/
    depends_on:
      - db
    environment: # docker의 -e 와 같은 부분
      - DJANGO_DEBUG=False
      - DJANGO_SECRET_KEY=
      - DJANGO_ALLOWED_HOST=localhost
      - SQL_DATABASE=postgresdb
      - SQL_USER=postgresuser
      - SQL_PASSWORD=postgrespass
      - SQL_HOST=db
      - SQL_PORT=5432

  db:
    container_name: db
    image: postgres
    environment: 
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgres/data
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80/tcp"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/staticfiles
    depends_on:
      - django