version: "3.8" # Compose file 버전

volumes:
  postgres_db: {}

services:
  django:
    container_name: django
    build: .
    restart: always
    command: gunicorn dcmStatus.wsgi --bind 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - ./static:/staticfiles
    depends_on:
      - db
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_SECRET_KEY=
      - DJANGO_ALLOWED_HOST=localhost
      - SQL_DATABASE=pgdb
      - SQL_USER=pguser
      - SQL_PASSWORD=pgpass
      - SQL_HOST=db
      - SQL_PORT=5432
  db:
    container_name: db
    image: postgres
    environment: 
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgres/data
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/staticfiles
    depends_on:
      - django