# Generated by Django 3.1.7 on 2021-04-11 03:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gallId', models.TextField(unique=True)),
                ('content', models.TextField(blank=True)),
                ('openingDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiniGall',
            fields=[
                ('gall_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawling.gall')),
            ],
            bases=('crawling.gall',),
        ),
        migrations.CreateModel(
            name='MinorGall',
            fields=[
                ('gall_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawling.gall')),
            ],
            bases=('crawling.gall',),
        ),
        migrations.CreateModel(
            name='StatPostCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('postCount', models.PositiveIntegerField()),
                ('gall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawling.gall')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('comparedToPreviousDay', models.IntegerField(null=True)),
                ('crawledDate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crawling.crawleddate')),
                ('gall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawling.gall')),
            ],
        ),
    ]
