# Generated by Django 3.1.7 on 2021-03-30 01:41

import crawling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_auto_20210327_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='comparedToPreviousday',
            field=models.IntegerField(default=crawling.models.Rank.comparedToPreviousday_default),
        ),
    ]
