# Generated by Django 3.1.7 on 2021-03-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0003_rank_comparedtopreviousday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='comparedToPreviousday',
            field=models.IntegerField(null=True),
        ),
    ]
